### ISSUE TITLE
Select with size option shows chevron

### ISSUE THREAD

**Issue by bgreay** [tailwindlabs/tailwindcss-forms#136]
### What version of @tailwindcss/forms are you using?

0.5.3

### What version of Node.js are you using?

16.18.0

### What browser are you using?

Chrome

### What operating system are you using?

Windows

### Reproduction repository

https://play.tailwindcss.com/MTlLIvHUfi

### Describe your issue

I have a select form element with a size attribute as I want multiple options to display. 
I do not have the "multiple" attribute as I do not want to allow multiple selections.
The chevron appears unless you add the multiple attribute.

![image](https://user-images.githubusercontent.com/61451/221149543-58d20adf-b2e5-4129-a0e1-f7d0a6c6eef5.png)

**Comment by thecrypticace** [comment]
I'll see what the consensus is on adding a check for the `size` attribute. In the meantime you can add this to your own project to mirror the `[multiple]` reset as long as it's not for `size=1` (which looks like a single select)

```css
@layer components {
  [size]:where(:not([size="1"])) {
    background-image: initial;
    background-position: initial;
    background-repeat: unset;
    background-size: initial;
    padding-right: 0.75rem;
    print-color-adjust: unset;
  }
}
```

Adding it to the components later + the use of `:where` will still let you use utilities to override the background properties.
