### ISSUE TITLE
Add ability to update/override pseudo for input search

### ISSUE THREAD

**Issue by chiefpansancolt** [tailwindlabs/tailwindcss-forms#16]
In input search, once words are typed an x shows up but when dark mode is used the x is not visible due to color, but there is no way to update this during the dark mode.

**Comment by RJFares** [comment]
+1

**Comment by cdock1029** [comment]
I got this to work for Chrome, you can tweak the brightness or use other filters...

```scss
html.dark {
    input[type='search']::-webkit-search-cancel-button {
      filter: grayscale(1) brightness(1.5);
    }
    input[type='date']::-webkit-calendar-picker-indicator {
      filter: invert(1);
    }
  }
```
