### ISSUE TITLE
Add coloured check marks

### ISSUE THREAD

**Issue by MarcelloTheArcane** [tailwindlabs/tailwindcss-forms#27]
I'm using a checkbox on a coloured background, and so I want the checkbox _box_ to be white, and the tick inside to be the same colour as the background.  Here's one made from an SVG I stole from here before Tailwind 2:

![image](https://user-images.githubusercontent.com/21159570/102519882-fb41f380-408a-11eb-839a-59d557aadc3a.png)

I'm trying to replicate this using just classes with Tailwind 2, but have been unable to so far:

![image](https://user-images.githubusercontent.com/21159570/102519947-0dbc2d00-408b-11eb-9084-654c960babdb.png)

```html
<input type="checkbox" class="ml-1 h-4 w-4 rounded border-gray-400 focus:border-raisin focus:ring-2 focus:ring-black text-white">
```

(I have a custom colour called 'raisin' which is `#27262c`)

**Comment by agusterodin** [comment]
Did you ever find an elegant solution?

**Comment by patrickgaskill** [comment]
Just ran into this one. I expected `bg-white text-purple` to work like your first example.

**Comment by agusterodin** [comment]
The best quick solution I came up with was adding this to my base styles:

```
[type='checkbox'].checkmark-gray:checked {
  background-image: url("data:image/svg+xml,%3csvg viewBox='0 0 16 16' fill='111827' xmlns='http://www.w3.org/2000/svg'%3e%3cpath d='M12.207 4.793a1 1 0 010 1.414l-5 5a1 1 0 01-1.414 0l-2-2a1 1 0 011.414-1.414L6.5 9.086l4.293-4.293a1 1 0 011.414 0z'/%3e%3c/svg%3e");
  @apply text-white;
}
```

So all I have to do is add a checkmark-gray class to the checkbox and it looks the way I want. Ideally there would be a way to generate `checkmark-[color]-[color number]` classes using the design system as the source of truth for colors in PostCSS. I didn't have time to look into it further since our sprints at work have been super tight.

Let me know if you find anything even more elegant.

**Comment by jenstornell** [comment]
Now we can control the background with the text color like `text-blue-500`. It means we have no color left to control the text color.

**To me the ideal solution would be:**

- `bg-` - Controls the checkbox background color.
- `text-` - Controls the checkbox text color.

Else we are stuck with just the text color.

**Comment by jenstornell** [comment]
I just made a heck of a hack. It's similar to agusterodin solution:

```css
@layer components {
  [type="checkbox"]:checked {
    background-image: url("data:image/svg+xml,%3csvg viewBox='0 0 16 16' fill='%23262626' xmlns='http://www.w3.org/2000/svg'%3e%3cpath d='M12.207 4.793a1 1 0 010 1.414l-5 5a1 1 0 01-1.414 0l-2-2a1 1 0 011.414-1.414L6.5 9.086l4.293-4.293a1 1 0 011.414 0z'/%3e%3c/svg%3e");
    @apply text-white border-gray-300;
  }

  [type="checkbox"]:checked:hover {
    @apply border-gray-300;
  }
}
```

**The input without the label looks like this:**

```html
<input type="checkbox" class="w-5 h-5 border border-gray-300 rounded-sm focus:ring-0 focus:ring-offset-0" />
```

*As you may notice I also removed the focus styles because I found it distracting and it's not default on checkboxes anyway.*

**The result is the below image:**

![localhost_tools_squares_ (2)](https://user-images.githubusercontent.com/927011/114983763-492c0400-9e91-11eb-8bc0-d8f19c827bbc.png)

See my previous comment for a solid suggestion to a solution.
