### ISSUE TITLE
Does not inherit config ring settings

### ISSUE THREAD

**Issue by sklawren** [tailwindlabs/tailwindcss-forms#52]
In my tailwind config, I have used theme extend ringColor to change the default color of my ring. It works on non-form elements, but on inputs, selects, etc. it still uses the tailwind default ringColor (blue-600, I think).

My expectation is that this plugin should inherit the ringColor, ringOpacity, etc. from the tailwind config file. Is this expectation correct and is this something that can be fixed?

**Comment by adevade** [comment]
Just discovered this as well as I was updating from the old Custom Forms plugin. Can't even override the color with utility classes. I'll see if I can find the problem and maybe open a PR.

**Comment by adevade** [comment]
Already one open with a related issue: #44. 

I also found that the latest published tag (v0.1.4) has the wrong CSS ring variable names. `--ring-*` instead of the new prefixed `--tw-ring-*`. I guess that's why I can't override the ring color with utilities?

Any reason for not tagging v0.2.0 yet?

**Comment by adamwathan** [comment]
Hey! We don't use the default ring color even by default (we use blue 600 which is not the default `ring` utility color in Tailwind), so I don't think it makes sense to inherit that from the user's config. We will pull in your own blue-600 if you've edited it, but if you want to just specify your own overrides for this plugin in general you should do so via CSS:

```css
@layer base {
  [type="text"],
  [type="email"]
  /* ... */ {
    border-color: pink;
  }

  /* ... */
}
```

**Comment by sklawren** [comment]
But the ring isn't border color.

![ring](https://user-images.githubusercontent.com/60169661/112780081-08f01780-9083-11eb-9b8e-94e75061a689.png)

**Comment by sklawren** [comment]
It would be a lot easier if we could just override the ring color in the config, and especially useful if we could use a dark theme, as well.

This is a lot of work inspecting the elements when they're focused and focus-visible just to get the various box shadows values that are being used.

```css
.dark {
    & input.focus-visible {
        box-shadow: 0 0 0 0 #1c273a, 0 0 0 3px #7d75c1, 0 0 #0000;
    }

    & select.focus-visible {
        box-shadow: 0 0 0 0 #1c273a, 0 0 0 3px #7d75c1, 0 0 #0000;
    }

    & select:focus {
        box-shadow: 0 0 0 0 #1c273a, 0 0 0 3px #7d75c1, 0 0 #0000;
    }

    & input[type='checkbox']:focus,
    & input[type='radio']:focus {
        box-shadow: 0 0 0 2px #1c273a, 0 0 0 4px #7d75c1, 0 0 #0000;
    }
}
```

**Comment by clluiz** [comment]
Same problem here. Any good solution to override these colors?

**Comment by sklawren** [comment]
@clluiz Since this is no longer an issue about inheriting ring color, but instead about a feature request to add a configuration setting, I've started a feature request thread here.

https://github.com/tailwindlabs/tailwindcss/discussions/3868#discussioncomment-543345

**Comment by rasmuscnielsen** [comment]
For anyone just wanting to tweak the default focus styles a bit, I found the following CSS to be a good starting point for my own use case:

```css
@layer base {
    [type='text']:focus,
    [type='email']:focus,
    [type='url']:focus,
    [type='password']:focus,
    [type='number']:focus,
    [type='date']:focus,
    [type='datetime-local']:focus,
    [type='month']:focus,
    [type='search']:focus,
    [type='tel']:focus,
    [type='time']:focus,
    [type='week']:focus,
    [multiple]:focus,
    textarea:focus,
    select:focus {
        --tw-ring-color: #93c5fd;
        border-color: var(--tw-ring-color);
    }

    [type="checkbox"],
    [type="radio"] {
        color: #3b82f6;
    }

    [type="checkbox"]:focus,
    [type="radio"]:focus {
        --tw-ring-color: #93c5fd;
    }

    button:focus,
    a:focus {
        box-shadow: 0 0 0 3px rgba(66, 153, 225, 0.5);
        border-color: #93c5fd;
        outline: none;
    }
}
```

(changes the ring and checbox/radio colors to a bit lighter blue than the default - colors can easily be changed to your preference)
