### ISSUE TITLE
Radio and Checkbox lose styling in prod mode

### ISSUE THREAD

**Issue by jacekschae** [tailwindlabs/tailwindcss-forms#55]
I'm wondering what i'm doing wrong 🤔. I have a form with `input`, `radio`, `select`, and `checkbox` elements. I know that my configuration with `@tailwindcss/forms` is valid since in dev mode; all form elements are displayed correctly -- with styling.
```bash
tailwindcss build ./src/dev/tailwind.css -o ./public/css/main.css
```

Yet when I run the production

```bash
NODE_ENV=production postcss build ./src/dev/tailwind.css -o ./public/css/main.css
```

I'm losing styling on `radio` and `checkbox` elements, `select` seems to be not impacted and I'm wondering why?

```css
/* tailwind.css */
@tailwind base;
@tailwind components;
@tailwind utilities;
```

```js
// tailwind.config.js
module.exports = {
  purge: {
    content: ["./public/**/*.html", "./src/main/**/*.cljs"]
  },
  darkMode: false, // or 'media' or 'class'
  theme: {
    extend: {},
  },
  variants: {
    extend: {},
  },
  plugins: [
    require('@tailwindcss/forms'),
  ],
}
```

```js
// postcss.config.js
const cssnano = require('cssnano');

module.exports = {
  plugins: [
    require('tailwindcss'),
    require('autoprefixer'),
    cssnano({ preset: 'default' }),
  ]
}
```

Output when running (all ok):

```bash
tailwindcss build ./src/dev/tailwind.css -o ./public/css/main.css
```
<img width="1700" alt="tw-build" src="https://user-images.githubusercontent.com/31179812/111084223-9d9a3780-8511-11eb-8bae-9172ce2b5f7c.png">

Output when running (radio and checkbox lose styling):

```bash
NODE_ENV=production postcss build ./src/dev/tailwind.css -o ./public/css/main.css
```
<img width="1700" alt="tw-prod" src="https://user-images.githubusercontent.com/31179812/111084228-9ffc9180-8511-11eb-9bc2-73dbe50c66bb.png">

Any ideas or pointes what I could change to make this work would be appreciated.

**Comment by jacekschae** [comment]
I fixed it with the release of tailwind-jit https://github.com/jacekschae/shadow-cljs-tailwindcss

**Comment by jtormey** [comment]
I'm seeing an issue that might be related to this, but am not 100% sure.

When building for production specifically, checkboxes lose their SVG background due to what looks like an invalid data URI. The following is what I see in the browser style inspector...

In development:

```css
[type='checkbox']:checked {
    background-image: url(data:image/svg+xml,%3csvg viewBox='0 0 16 16' fill='white' xmlns='http://www.w3.org/2000/svg'%3e%3cpath d='M12.207 4.793a1 1 0 010 1.414l-5 5a1 1 0 01-1.414 0l-2-2a1 1 0 011.414-1.414L6.5 9.086l4.293-4.293a1 1 0 011.414 0z'/%3e%3c/svg%3e);
}
```

In production:

```css
[type=checkbox]:checked {
    background-image: url(data:image/svg+xml;charset=utf-8,%3Csvg viewBox='0 0 16 16' fill='%23fff' xmlns='http://www.w3.org/2000/svg'%3E%3Cpath d='M12.207 4.793a1 1 0 10 1.414 NaN NaNlNaN NaNa1 1 0 1-1.414 NaN NaNlNaN NaNa1 1 0 11.414-1.414 NaN NaNlNaN NaN NaN NaNa1 1 0 11.414 0 NaN NaNz'/%3E%3C/svg%3E);
}
```

No other styles are affected, from what I can tell. The `NaN`s in the data URI seem to be the problem to me, but I'm not sure where they would be coming from.

This was tested using `@tailwindcss/jit 0.1.18` and `@tailwindcss/forms 0.3.1`. For context, I also have `@tailwindcss/ui 0.7.2` and `@tailwindcss/aspect-ratio 0.2.0` installed and in use. I'm happy to provide more information if needed!
